### PR TITLE
[ Backend ] - API for Task Deletion

### PR DESCRIPTION
**Pull request by JavidSumra**
This PR Resolves,
Issue #18 
Title : [Backend] API Endpoint For Tasks Delete

Path : `/api/v1/tasks/delete/:id`,
Method : `delete`,

I am Contributing Under JWOC 2024

### CODE REVIEW

**Comment by sayan404** [comment]
Resolve the conflicts and make one more commit. @JavidSumra

**Comment by JavidSumra** [comment]
I'll do it right now please check @sayan404 Sir

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir Please Check My PR All Conflict Resolved And Please Add `Labels`

**Comment by sayan404** [comment]
Good job @JavidSumra .

**Pull request merged**
