### PR TITLE
Add a local installation video

### LINKED ISSUE #10: [Feature]: Enhance Contributor Onboarding -Add Local Installation Video to README
Description
Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

Expected Outcome:
The addition of a video tutorial in the README, demonstrating the step-by-step process of installing the project locally, will make it easier for contributors, especially those new to the codebase.

Proposed Content:
A short video covering the following:

Cloning the repository.
Installing dependencies.
Configuring any necessary settings.
Running the project locally.

Problem
Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

Proposed Solution
Record a concise video for that.

Contributing under JWOC.

### PR DESCRIPTION
**Pull request by rahat2134**
fix #10 
add a local installation video for contributors.

### CODE REVIEW

**Comment by rahat2134** [comment]
@sayan404 PTAL.

**Comment by sayan404** [comment]
You explained pretty well, but there's one thing you missed; you didn't talk about the environment variable setup. Please include that part as well. @rahat2134  if you need info about env variables, you can check the existing README.md file.

**Comment by rahat2134** [comment]
@sayan404 but this pr was mainly for frontend purpose.

**Comment by sayan404** [comment]
> @sayan404 but this pr was mainly for frontend purpose.

It wasn't mentioned anywhere in Issue #16 . In this type of full-stack repo, both the frontend and backend setup are much needed as there are some issues with environment variables. Anyway, if you need any guidance on backend setup, feel free to ask for it. @rahat2134

**Comment by rahat2134** [comment]
@sayan404 no problem give me sometime i will update you on same, and please if possible kindly increase difficulty level to hard for that . Thank You.

**Comment by sayan404** [comment]
> @sayan404 no problem give me sometime i will update you on same, and please if possible kindly increase difficulty level to hard for that . Thank You.

Do not worry fix the issue, I will promote the label as hard.

**Comment by sayan404** [comment]
are you still working in this issue @rahat2134 .

**Pull request closed without merging**
