### PR TITLE
Changed login form container for better usability when in mobile view

### PR DESCRIPTION
**Pull request by sarthakroy107**
Screenshot_20240118_193026

### CODE REVIEW

**Comment by sayan404** [comment]
Can you please give a screenshot of the register page ? @sarthakroy107

**Comment by sayan404** [comment]
The dekstop view is distored .
Screenshot 2024-01-18 221609

**Comment by sarthakroy107** [comment]
Screenshot of registration page
Screenshot_20240118_231816

 I have made changes in media query, so page layout will not get distorted in desktop view

Screenshot_20240118_231849

**Comment by sayan404** [comment]
seems like you have not pushed your latest commits in this branch. @sarthakroy107

**Comment by sarthakroy107** [comment]
I have not changed anything after opening PR.  
UI is not distorting in desktop view as you can see in the above screenshot. 
@sayan404

**Comment by sayan404** [comment]
okay. Good work . I am merging this PR.

**Pull request merged**
