### PR TITLE
[ Backend ] - Task Details Update Route

### PR DESCRIPTION
**Pull request by JavidSumra**
This PR Resolves,
Issue #24 
Title : [Backend] API Endpoint to Tasks Update

Path : `/api/v1/tasks/update/:id`,
Method : `PUT`,

I am Contributing Under JWOC 2024

### CODE REVIEW

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir Please Checkout My PR.

**Comment by sayan404** [comment]
There is an edge case that is not handled in your code. If any of the data does not come within taskName, dueDate, priority, or description, it will cause an error. @JavidSumra

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir Changes Done Please Check Onece.

**Comment by sayan404** [comment]
good job ! @JavidSumra

**Pull request merged**
