### PR TITLE
Fixing Issue of Login Route

### PR DESCRIPTION
**Pull request by JavidSumra**
Issue #29 
Title : Bug: Currently, we can access the /login route even in a logged-in situation. 
Fixing Issue of Login Route By Use of LocalStorage

### CODE REVIEW

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir Please Checkout My PR

**Comment by sayan404** [comment]
please add the  VITE_API_ENDPOINT_DEV and VITE_API_ENDPOINT_PROD both things and raise a commit in production (PROD) mode . @JavidSumra

**Comment by JavidSumra** [comment]
Hey @sayan404 Sir I am Unable to Understand your point I think you need to set API Endpoint For Production?

**Comment by sayan404** [comment]
Yea , just add this to variables in the .env 
VITE_API_ENDPOINT_DEV=http://localhost:8080
VITE_API_ENDPOINT_PROD=https://taskpulse.onrender.com
when you will be pushing changes in the remote branch use VITE_API_ENDPOINT_PROD in the place of VITE_API_ENDPOINT otherwise use VITE_API_ENDPOINT_DEV (in development mode) @JavidSumra

**Comment by JavidSumra** [comment]
Changes Done @sayan404 Sir

**Comment by sayan404** [comment]
good job . @JavidSumra

**Pull request merged**
